# @format

BOT:
  OWNERS: [""]
  ADMINS: [""]

LINKS:
  SUPPORT: "https://discord.gg/nexhq | https://discord.gg/jsk"
  MONGO_URI: "mongodb+srv://Saavan:6969@saavan.mzc7ria.mongodb.net/mmmmmm"

SPOTIFY:
  ID: "e6f84fbec2b44a77bf35a20c5ffa54b8"
  SECRET: "98f461b962443cfaf9539c610e2ea81"

MANAGER:
  OWNER: "" 
  TOKEN: "YOUR BOT TOKEN"  

FUEGO:
  PREFIX: "1"
  EMOJIS: "black"
  COLOR: "#555555"
  SHARDS: 1
  PER_CLUSTER: 1
  TOKEN: "YOUR BOT TOKEN"
  TOPGGAUTH: ""


WEBHOOKS:
  ERROR: ""
  STATIC: ""
  PLAYER: ""
  SERVER: ""
  COMMAND: ""
